Parameters:
  MFA:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Require MFA when assuming into a Role.
  AllowedRegions:
    Type: String
    Description: Comma separated list of Regions that can be used in your AWS Accounts.
  MaxSessionDuration:
    Type: Number
    Default: 28800
    Description: Maximum Duration you can set when assuming a role.
  ExportPrefix:
    Type: String
    Default: assumable-roles
Conditions:
  HasMFAEnabled: !Equals 
    - 'true'
    - !Ref MFA
Resources:
  AssumableAdminRole:
    Properties:
      MaxSessionDuration: !Ref MaxSessionDuration
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            AWS: 037729278610
          Action: 'sts:AssumeRole'
          Condition: !If 
            - HasMFAEnabled
            - Bool:
                'aws:MultiFactorAuthPresent': true
            - !Ref 'AWS::NoValue'
      Policies:
        - PolicyName: AdminAccess
          PolicyDocument:
            Statement:
              - Sid: AdminAccess
                Effect: Allow
                Action:
                  - '*'
                Resource:
                  - '*'
      RoleName: AssumableAdminRole
    Type: 'AWS::IAM::Role'
Outputs:
  AssumableAdminRoleArn:
    Value: !GetAtt 
      - AssumableAdminRole
      - Arn
    Export:
      Name: !Sub '${ExportPrefix}:AssumableAdminRoleArn'
